# Generated by Django 5.0.4 on 2024-08-29 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("order_date", models.DateField()),
                ("invoice_date", models.DateField()),
                ("invoice_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("invoice_amount_inc_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency_code", models.CharField(max_length=3)),
                ("shop_ref", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_id", models.CharField(blank=True, max_length=10, null=True)),
                ("typo3_user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_user_id_sync", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_id", models.CharField(blank=True, max_length=100, null=True)),
                ("person_no", models.CharField(blank=True, max_length=100, null=True)),
                ("is_sync_to_erp", models.BooleanField(default=False)),
                ("is_sync_to_shop", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="customer_number",
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoice",
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_id", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_price_inc_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shop_ref", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_sales_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_user_id_sync", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_id", models.CharField(blank=True, max_length=100, null=True)),
                ("download", models.BooleanField(default=False)),
                ("print_on_demand", models.BooleanField(default=False)),
                ("logistic", models.BooleanField(default=False)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("line_no", models.CharField(max_length=50)),
                ("is_sync_to_erp", models.BooleanField(default=False)),
                ("is_sync_to_shop", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="customer_number",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_items",
                        to="orders.salesinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoice_item",
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("order_date", models.DateField()),
                ("delivery_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_inc_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency_code", models.CharField(max_length=3)),
                ("shop_ref", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_id", models.CharField(blank=True, max_length=10, null=True)),
                ("shop_shipping_number", models.CharField(blank=True, max_length=100, null=True)),
                ("delivery_address_code", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_user_id_sync", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_id", models.CharField(blank=True, max_length=100, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("shipping_costs", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("credit_card_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saferpay_id", models.CharField(blank=True, max_length=255, null=True)),
                ("web_customer_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("export_id", models.CharField(blank=True, max_length=100, null=True)),
                ("person_no", models.CharField(blank=True, max_length=100, null=True)),
                ("lines", models.JSONField(blank=True, default=list, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="customer_number",
                    ),
                ),
            ],
            options={
                "db_table": "sales_order",
            },
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="order_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.salesorder", to_field="order_number"
            ),
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(max_length=50)),
                ("customer_id", models.CharField(max_length=50)),
                ("item_id", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("open_quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_price_inc_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("download", models.BooleanField(default=False)),
                ("print_on_demand", models.BooleanField(default=False)),
                ("logistic", models.BooleanField(default=False)),
                ("shop_ref", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_sales_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_user_id_sync", models.CharField(blank=True, max_length=100, null=True)),
                ("typo3_id", models.CharField(blank=True, max_length=100, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("line_no", models.CharField(max_length=50)),
                ("is_sync_to_erp", models.BooleanField(default=False)),
                ("is_sync_to_shop", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.salesorder"
                    ),
                ),
            ],
            options={
                "db_table": "sales_order_item",
            },
        ),
    ]
