# Generated by Django 5.0.4 on 2024-09-03 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesinvoice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="salesinvoice",
            name="is_sync_to_erp",
        ),
        migrations.RemoveField(
            model_name="salesinvoice",
            name="is_sync_to_shop",
        ),
        migrations.RemoveField(
            model_name="salesinvoice",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="is_sync_to_erp",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="is_sync_to_shop",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="salesorderitem",
            name="is_sync_to_shop",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesorder",
            name="is_sync_to_erp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
