# Generated by Django 5.0.4 on 2024-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_shopsalesorder_typo3_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsalesorder",
            name="shop_customer_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shopsalesorder",
            name="erp_order_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
