# Generated by Django 5.0.4 on 2024-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_shopsalesorder_shop_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopsalesorder",
            name="shop_customer_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
