# Generated by Django 5.0.4 on 2024-09-10 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("firm_no", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name2", models.CharField(blank=True, max_length=255, null=True)),
                ("name3", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("post_box", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code_post_box", models.CharField(blank=True, max_length=20, null=True)),
                ("city_post_box", models.CharField(blank=True, max_length=100, null=True)),
                ("email_z", models.EmailField(max_length=254)),
                ("phone_z", models.CharField(blank=True, max_length=50, null=True)),
                ("fax_z", models.CharField(blank=True, max_length=50, null=True)),
                ("language_code", models.CharField(blank=True, max_length=5, null=True)),
                ("country_code", models.CharField(blank=True, max_length=5, null=True)),
                ("advertising", models.BooleanField(default=False)),
                ("newsletter", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("login_user", models.CharField(max_length=255)),
                ("login_password", models.CharField(max_length=255)),
                ("web_customer_id", models.CharField(blank=True, max_length=20, null=True)),
                ("customer_no", models.CharField(max_length=20)),
                ("customer_price_group", models.CharField(blank=True, max_length=50, null=True)),
                ("deb_discount_group", models.CharField(blank=True, max_length=50, null=True)),
                ("invoice_discount_code", models.CharField(blank=True, max_length=50, null=True)),
                ("vat", models.CharField(blank=True, max_length=5, null=True)),
                ("payment_method_code", models.CharField(blank=True, max_length=50, null=True)),
                ("payment_terms_code", models.CharField(blank=True, max_length=50, null=True)),
                ("vat_reg_number", models.CharField(blank=True, max_length=50, null=True)),
                ("membership", models.CharField(blank=True, max_length=50, null=True)),
                ("access_member_area", models.BooleanField(default=False)),
                ("access_personal", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "firm",
            },
        ),
        migrations.CreateModel(
            name="FirmPerson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Name")),
                ("name2", models.CharField(blank=True, max_length=255, null=True, verbose_name="Name 2")),
                ("name3", models.CharField(blank=True, max_length=255, null=True, verbose_name="Name 3")),
                ("contact", models.CharField(blank=True, max_length=255, null=True, verbose_name="Contact")),
                ("address", models.CharField(blank=True, max_length=255, null=True, verbose_name="Address")),
                ("address2", models.CharField(blank=True, max_length=255, null=True, verbose_name="Address 2")),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True, verbose_name="Postal Code")),
                ("city", models.CharField(blank=True, max_length=100, null=True, verbose_name="City")),
                ("post_box", models.CharField(blank=True, max_length=100, null=True, verbose_name="Post Box")),
                (
                    "postal_code_post_box",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="Postal Code Post Box"),
                ),
                (
                    "city_post_box",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="City Post Box"),
                ),
                ("country_code", models.CharField(blank=True, max_length=2, null=True, verbose_name="Country Code")),
                ("email_g", models.EmailField(blank=True, max_length=255, null=True, verbose_name="General Email")),
                ("phone_g", models.CharField(blank=True, max_length=20, null=True, verbose_name="General Phone")),
                ("mobile_g", models.CharField(blank=True, max_length=20, null=True, verbose_name="General Mobile")),
                ("invoice_to", models.CharField(blank=True, max_length=10, null=True, verbose_name="Invoice To")),
                (
                    "firm_no",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firm.firm",
                        to_field="firm_no",
                        verbose_name="Firm Number",
                    ),
                ),
                (
                    "person_no",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="customer_number",
                        verbose_name="Person Number",
                    ),
                ),
            ],
            options={
                "db_table": "firm_person",
            },
        ),
    ]
