# Generated by Django 5.0.4 on 2024-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Norm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("unit_price", models.CharField(max_length=10)),
                ("vat_print", models.DecimalField(decimal_places=2, max_digits=5)),
                ("vat_download", models.DecimalField(decimal_places=2, max_digits=5)),
                ("discount_group", models.CharField(max_length=10)),
                ("sales_unit_text", models.CharField(max_length=50)),
                ("stock_status", models.CharField(max_length=10)),
                ("stock", models.IntegerField()),
                ("price_includes_vat", models.BooleanField(default=False)),
                ("sort_key", models.CharField(max_length=10)),
                ("special_offer", models.BooleanField(default=False)),
                ("new_item", models.BooleanField(default=False)),
                ("delivery_times_in_days", models.CharField(max_length=10)),
                ("spec_weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("no2", models.CharField(blank=True, max_length=50, null=True)),
                ("description2", models.TextField(blank=True, null=True)),
                ("issue", models.CharField(max_length=10)),
                ("comment", models.CharField(max_length=10)),
                ("standard_draft", models.CharField(max_length=10)),
                ("fidaskey", models.CharField(max_length=20)),
                ("edvnr", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=10)),
                ("pages", models.IntegerField()),
                ("perinorm_country_code", models.CharField(blank=True, max_length=10, null=True)),
                ("date_objection", models.CharField(blank=True, max_length=10, null=True)),
                ("snv_tk", models.CharField(blank=True, max_length=10, null=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("switec_info_0", models.CharField(blank=True, max_length=10, null=True)),
                ("switec_info_1", models.CharField(blank=True, max_length=10, null=True)),
                ("switec_info_6", models.CharField(blank=True, max_length=10, null=True)),
                ("switec_info_9", models.CharField(blank=True, max_length=10, null=True)),
                ("alarm_revision", models.CharField(blank=True, max_length=10, null=True)),
                ("belongs_to_wi", models.CharField(max_length=50)),
                ("rule", models.CharField(max_length=50)),
                ("dok_art", models.CharField(max_length=50)),
                ("text_of_withdrawal", models.TextField(blank=True, null=True)),
                ("date_of_withdrawal", models.CharField(blank=True, max_length=10, null=True)),
                ("dok_nr_alternative", models.CharField(max_length=50)),
                ("norm_valid_from", models.CharField(blank=True, max_length=10, null=True)),
                ("dok_nr", models.CharField(max_length=50)),
                ("approved_from", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "norm",
            },
        ),
    ]
