# Generated by Django 5.0.4 on 2024-09-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonExpertRight",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("committee", models.CharField(max_length=50)),
                ("function", models.CharField(blank=True, max_length=50, null=True)),
                ("com_description", models.CharField(blank=True, max_length=255, null=True)),
                ("com_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("com_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("com_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_column="customer_number",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        to_field="customer_number",
                    ),
                ),
            ],
            options={
                "db_table": "person_expert_right",
            },
        ),
    ]
