from django.db import models

class Norm(models.Model):
    no = models.CharField(max_length=50)
    description = models.TextField()
    unit_price = models.CharField(max_length=10)
    vat_print = models.DecimalField(max_digits=5, decimal_places=2)
    vat_download = models.DecimalField(max_digits=5, decimal_places=2)
    discount_group = models.CharField(max_length=10)
    sales_unit_text = models.CharField(max_length=50)
    stock_status = models.CharField(max_length=10)
    stock = models.IntegerField()
    price_includes_vat = models.BooleanField(default=False)
    sort_key = models.CharField(max_length=10)
    special_offer = models.BooleanField(default=False)
    new_item = models.BooleanField(default=False)
    delivery_times_in_days = models.CharField(max_length=10)
    spec_weight = models.DecimalField(max_digits=10, decimal_places=3)
    no2 = models.CharField(max_length=50, blank=True, null=True)
    description2 = models.TextField(blank=True, null=True)
    issue = models.CharField(max_length=10)
    comment = models.CharField(max_length=10)
    standard_draft = models.CharField(max_length=10)
    fidaskey = models.CharField(max_length=20)
    edvnr = models.CharField(max_length=20)
    status = models.CharField(max_length=10)
    pages = models.IntegerField()
    perinorm_country_code = models.CharField(max_length=10, blank=True, null=True)
    date_objection = models.CharField(max_length=10, blank=True, null=True)
    snv_tk = models.CharField(max_length=50, blank=True, null=True)
    author = models.CharField(max_length=100, blank=True, null=True)
    switec_info_0 = models.CharField(max_length=10, blank=True, null=True)
    switec_info_1 = models.CharField(max_length=10, blank=True, null=True)
    switec_info_6 = models.CharField(max_length=10, blank=True, null=True)
    switec_info_9 = models.CharField(max_length=10, blank=True, null=True)
    alarm_revision = models.CharField(max_length=10, blank=True, null=True)
    belongs_to_wi = models.CharField(max_length=50)
    rule = models.CharField(max_length=50)
    dok_art = models.CharField(max_length=50)
    text_of_withdrawal = models.TextField(blank=True, null=True)
    date_of_withdrawal = models.CharField(max_length=10, blank=True, null=True)
    dok_nr_alternative = models.CharField(max_length=50)
    norm_valid_from = models.CharField(max_length=10, blank=True, null=True)
    dok_nr = models.CharField(max_length=50)
    approved_from = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f'{self.no} - {self.description}'
    class Meta:
        db_table = 'norm'  # This will change the table name to "customer"