# Generated by Django 5.0.4 on 2024-09-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="firm_no",
        ),
    ]
