# Generated by Django 5.0.4 on 2024-09-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_person_firm_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="customer_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
