# Generated by Django 5.0.4 on 2024-09-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_person_customer_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerShippingAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery_address_code", models.CharField(max_length=20, verbose_name="Delivery Address Code")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("name2", models.CharField(blank=True, max_length=100, null=True, verbose_name="Name 2")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("address2", models.CharField(blank=True, max_length=255, null=True, verbose_name="Address 2")),
                ("postal_code", models.CharField(max_length=10, verbose_name="Postal Code")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("country_code", models.CharField(max_length=2, verbose_name="Country Code")),
                ("typo3_id", models.CharField(blank=True, max_length=20, null=True, verbose_name="TYPO3 ID")),
                ("typo3_user_id", models.CharField(blank=True, max_length=20, null=True, verbose_name="TYPO3 User ID")),
                (
                    "typo3_user_id_sync",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="TYPO3 User ID Sync"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        to_field="customer_number",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Shipping Address",
                "verbose_name_plural": "Customer Shipping Addresses",
                "db_table": "customer_shipping_address",
            },
        ),
    ]
