# Generated by Django 5.0.4 on 2024-09-17 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customershippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="lastname",
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
