# Generated by Django 5.0.4 on 2024-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_customer_firstname_remove_customer_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="login_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="web_shop_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
