# Generated by Django 5.0.4 on 2024-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customer_login_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="magazine_suv",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
